/**
 * The emoji table (generated by scripts/build-emoji-data.mjs) and the lookups
 * the reaction picker and the composer's `:shortcode` autocomplete share. The
 * table is its own chunk, loaded the first time anything asks.
 */

export interface Emoji {
  emoji: string;
  /** Slack's names first; the first is the one shown. */
  shortcodes: string[];
  group: number;
  keywords: string[];
}

export const EMOJI_GROUPS: ReadonlyArray<{ id: number; label: string; icon: string }> = [
  { id: 0, label: 'Smileys', icon: '😀' },
  { id: 1, label: 'People', icon: '👋' },
  { id: 3, label: 'Nature', icon: '🐻' },
  { id: 4, label: 'Food', icon: '🍔' },
  { id: 5, label: 'Travel', icon: '✈️' },
  { id: 6, label: 'Activities', icon: '⚽' },
  { id: 7, label: 'Objects', icon: '💡' },
  { id: 8, label: 'Symbols', icon: '❤️' },
  { id: 9, label: 'Flags', icon: '🏁' },
];

/** The reactions offered before the full picker, in Slack's spirit. */
export const QUICK_REACTIONS: readonly string[] = ['👍', '👀', '❓', '✅', '❤️'];

let table: Promise<Emoji[]> | null = null;

/** The whole table. A failed load is not kept: the next caller tries again. */
export function loadEmoji(): Promise<Emoji[]> {
  table ??= import('./emoji-data.json').then((module) =>
    (module.default as Array<[string, string, number, string]>).map(([emoji, codes, group, keywords]) => ({
      emoji,
      shortcodes: codes.split(' '),
      group,
      keywords: keywords ? keywords.split(' ') : [],
    })),
  );
  table.catch(() => { table = null; });
  return table;
}

/**
 * Emoji matching a query, best first: a shortcode starting with it, then a
 * shortcode containing it, then a keyword starting with it. Table order
 * breaks ties, which keeps the common faces ahead of the obscure ones.
 */
export function findEmoji(all: readonly Emoji[], query: string, limit = Infinity): Emoji[] {
  const q = query.trim().toLowerCase().replace(/^:|:$/g, '');
  if (!q) return all.slice(0, limit);
  const ranked: Array<[number, number, Emoji]> = [];
  all.forEach((entry, index) => {
    let rank = -1;
    if (entry.shortcodes.some((code) => code.startsWith(q))) rank = 0;
    else if (entry.shortcodes.some((code) => code.includes(q))) rank = 1;
    else if (entry.keywords.some((word) => word.startsWith(q))) rank = 2;
    if (rank >= 0) ranked.push([rank, index, entry]);
  });
  ranked.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  return ranked.slice(0, limit).map(([, , entry]) => entry);
}

/** The shortcode to show for an emoji, e.g. `thumbsup` rather than `+1`. */
export function displayShortcode(entry: Emoji, query = ''): string {
  const q = query.toLowerCase();
  return entry.shortcodes.find((code) => q && code.startsWith(q))
    ?? entry.shortcodes.find((code) => /^[a-z]/.test(code))
    ?? entry.shortcodes[0];
}

/**
 * Emoji whose Slack name matches what follows the colon, as Slack's list
 * orders them: names starting with the query before names containing it, and
 * within each the shortest name first, so `:hear` offers ❤️ `heart` ahead of
 * 😍 `heart_eyes`. Keywords are left to the picker's search; here they only
 * surface emoji whose names look unrelated to what was typed.
 */
export function shortcodeSuggestions(all: readonly Emoji[], query: string, limit: number): Array<{ emoji: string; shortcode: string }> {
  const q = query.toLowerCase();
  const ranked: Array<{ rank: number; length: number; index: number; emoji: string; shortcode: string }> = [];
  all.forEach((entry, index) => {
    const prefix = entry.shortcodes.filter((code) => code.startsWith(q));
    const matched = prefix.length > 0 ? prefix : entry.shortcodes.filter((code) => code.includes(q));
    if (matched.length === 0) return;
    const shortcode = matched.reduce((best, code) => (code.length < best.length ? code : best));
    ranked.push({ rank: prefix.length > 0 ? 0 : 1, length: shortcode.length, index, emoji: entry.emoji, shortcode });
  });
  ranked.sort((a, b) => a.rank - b.rank || a.length - b.length || a.index - b.index);
  return ranked.slice(0, limit).map(({ emoji, shortcode }) => ({ emoji, shortcode }));
}
