/**
 * Session Review Service
 *
 * Generates post-session analysis with narrative summary and recommendations
 * for Claude improvements (CLAUDE.md, hooks, skills).
 *
 * Uses turns (session history) as the primary data source.
 */

import type Anthropic from '@anthropic-ai/sdk';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import type Database from 'better-sqlite3';
import { createLogger } from '../infrastructure/logger.js';
import { backgroundTextClient, backgroundProvenance, type BackgroundTextClient } from '../infrastructure/background-text-client.js';
import { DatabaseProvider } from '../infrastructure/database-provider.js';
import { SessionAnalysisService } from './session-analysis-service.js';
import { SessionInfoService } from '../sessions/session-info-service.js';
import { TurnCaptureService, Turn } from '../sessions/turn-capture-service.js';
import { ClaudeHistoryReader } from '../sessions/claude-history-reader.js';
import { readMessages } from '../../harness/event-message-reader.js';
import { REVIEW_ITEM_ID_PREFIXES, type StoredRecommendation } from '../../types/index.js';
import type { UnifiedMessage } from '../../types/unified-messages.js';
import { getCostTracker } from '../infrastructure/cost-tracker.js';
import { geminiService } from '../gemini-service.js';
import { getEventJournal } from '../infrastructure/event-journal.js';
import { parseJson } from '../../utils/json.js';
import { allowGeneration } from '../infrastructure/generation-gates.js';
import { CONFIG_FILE } from '@/utils/constants.js';

const logger = createLogger('SessionReviewService');

/** Review model. Alias-only ID, latest Opus tier. */
const REVIEW_MODEL = 'claude-opus-5-5';

/**
 * Pinned off. On the 5-family an OMITTED `thinking` means adaptive thinking is
 * ON (measured 2026-08-28: opus-5 emitted a thinking block even for a
 * one-word reply). This call has a 4,000-token cap and parses a JSON object
 * out of the text — adaptive thinking spending that cap produces exactly the
 * truncated-mid-JSON parse failure the code below guards against.
 */
const REVIEW_THINKING: Anthropic.ThinkingConfigParam = { type: 'disabled' };

// =============================================================================
// Types
// =============================================================================

interface FileChange {
  sessionId: string;
  turnNumber: number;
  toolName: string;
  filePath: string;
  oldString: string | null;
  newString: string;
}

interface FileChangeSummary {
  relativePath: string;
  turnNumbers: number[];
  editCount: number;
  writeCount: number;
  linesAdded: number;
  linesRemoved: number;
  /** Brief description of what changed (first edit's diff summary) */
  changeSummary: string;
}

interface GroupedEvent {
  text: string;
  icon: string;
}

interface DetailedTurnEvidence {
  turnNumber: number;
  userMessage: string;
  assistantResponse: string;
  tools: string[];
}

interface Skill {
  id?: string;           // Added during processing
  name: string;          // Slash-command name (lowercase, hyphens, e.g., "fix-issue")
  description: string;   // When Claude should use this skill (for auto-invocation)
  instructions: string;  // What the skill teaches Claude to do (the SKILL.md body)
  hasScript?: boolean;   // Whether this needs a bundled script (e.g., Python/Bash)
  scriptPurpose?: string; // If hasScript, what the script would do
}

interface Guardrail {
  id?: string;           // Added during processing
  type: string;          // pre-commit, test, CI check, etc.
  prevents: string;      // What class of problem this catches
  implementation: string; // Specific implementation details
}

interface ReviewAnalysis {
  // Brief narrative summary of the session
  summary: {
    goal: string;       // What the session set out to do
    outcome: string;    // What actually happened (1-2 sentences)
  };
  // Grouped events generated by Opus from turns - user-facing narrative
  groupedEvents: {
    friction: GroupedEvent[];  // Problems, blockers, confusion
    built: GroupedEvent[];     // Work done, changes made
    learned: GroupedEvent[];   // Insights, completions, decisions
  };
  metrics: {
    duration: string;
    messages: number;
    toolUses: number;
    errors: number;
    filesEdited: number;
  };
  // V4: Skills - domain-specific diagnostic techniques (VERY RARE)
  skills: Skill[];
  // V4: Guardrails - concrete automation to prevent friction
  guardrails: Guardrail[];
  // Legacy: still supported for backwards compatibility
  recommendations: Array<{
    id: string;
    target: 'project_instructions' | 'global_instructions' | 'codebase';
    friction: string;      // What went wrong or was inefficient
    action: string;        // Specific action to take
    rationale: string;     // Why this helps future sessions
  }>;
  rootCauses: Array<{
    surface: string;       // What visibly went wrong
    root: string;          // The fundamental issue underneath
    preventable: string;   // How this could have been avoided
  }>;
  claudeAnalysis: {
    strengths: string[];   // What Claude did well
    weaknesses: string[];  // Where Claude could improve
    keyInsight: string;    // One concrete thing to do differently
  };
  userFeedback: {
    effective: string[];     // What the user did well
    opportunities: string[]; // Where different user behavior might help
    keyInsight: string;      // One tip for the user
  };
  // Project path for project_instructions recommendations
  projectPath: string | null;
  // Session context from insights (project, area, mission)
  context?: { project: string; area: string | null; mission: string } | null;
  // Which provider generated this review (for UI display)
  reviewProvider?: 'opus' | 'gemini';
}

export type ReviewProvider = 'opus' | 'gemini';

interface ReviewData {
  sessionId: string;
  context: { mission?: string; project?: string; area?: string | null; scope?: string } | null;
  turns: Turn[];
  metrics: Record<string, unknown>;
  recentCommits?: string[];
  fileChangeSummaries?: FileChangeSummary[];
  detailedTurnEvidenceSection?: string;
  projectPath?: string;
}

interface ReviewResult {
  summary: ReviewAnalysis['summary'];
  groupedEvents: ReviewAnalysis['groupedEvents'];
  skills: Omit<Skill, 'id'>[];
  guardrails: Omit<Guardrail, 'id'>[];
  recommendations: Omit<ReviewAnalysis['recommendations'][0], 'id'>[];
  rootCauses: ReviewAnalysis['rootCauses'];
  claudeAnalysis: ReviewAnalysis['claudeAnalysis'];
  userFeedback: ReviewAnalysis['userFeedback'];
}

// =============================================================================
// Service
// =============================================================================

export class SessionReviewService {
  private static instance: SessionReviewService;
  private db: Database.Database;
  private analysisService: SessionAnalysisService;
  private sessionInfoService: SessionInfoService;
  private turnCaptureService: TurnCaptureService;
  private historyReader: ClaudeHistoryReader;

  private constructor() {
    this.db = DatabaseProvider.getInstance().getDb();
    this.analysisService = SessionAnalysisService.getInstance();
    this.sessionInfoService = SessionInfoService.getInstance();
    this.turnCaptureService = TurnCaptureService.getInstance();
    this.historyReader = new ClaudeHistoryReader();
  }

  static getInstance(): SessionReviewService {
    if (!SessionReviewService.instance) {
      SessionReviewService.instance = new SessionReviewService();
    }
    return SessionReviewService.instance;
  }

  private getClient(): BackgroundTextClient {
    const client = backgroundTextClient.getClient('sessionReview');
    if (!client) {
      throw new Error(
        'Anthropic client unavailable. Configure an Anthropic API key or active hosted proxy credentials.'
      );
    }
    return client;
  }

  async analyzeForReview(sessionIdInput: string, forceRefresh = false, provider: ReviewProvider = 'opus'): Promise<ReviewAnalysis> {
    logger.info('Starting session review analysis', { sessionId: sessionIdInput.slice(0, 8), forceRefresh, provider });
    getEventJournal().record({
      event: 'review.started',
      component: 'SessionReviewService',
      sessionId: sessionIdInput,
      fields: { forceRefresh, provider },
    });

    // Initialize services
    await this.analysisService.initialize();
    await this.sessionInfoService.initialize();

    // Resolve short session ID to full ID (needed for FK constraints)
    const sessionId = await this.sessionInfoService.resolveSessionId(sessionIdInput) || sessionIdInput;
    if (sessionId !== sessionIdInput) {
      logger.debug('Resolved session ID', { from: sessionIdInput, to: sessionId.slice(0, 8) });
    }

    // Resolve all linked session IDs (conv-* + all segment provider UUIDs).
    // A unified conversation may span multiple segments when Claude Code runs out of
    // context and continues — messages/changes can be stored under different IDs.
    const allSessionIds = await this.resolveAllLinkedSessionIds(sessionId);
    const isMultiSegment = allSessionIds.length > 1;
    if (isMultiSegment) {
      logger.info('Multi-segment session detected for review', {
        primaryId: sessionId.slice(0, 8),
        allIds: allSessionIds.map(id => id.slice(0, 8)),
        segmentCount: allSessionIds.length,
      });
    }

    // Wait for any in-flight turn captures to settle before counting turns.
    // Without this, a review triggered right after session completion can race
    // with the turn capture and miss the final turn(s).
    await this.turnCaptureService.waitForPendingCaptures(allSessionIds);

    // Get turns (session history) - needed for cache staleness check
    // Aggregate across all linked IDs to catch turns stored under any segment
    const turns = await this.getAggregatedTurns(allSessionIds);
    const currentTurnCount = turns.length;

    // Check cache - use provider-specific cache key for Gemini
    const cacheKey = provider === 'gemini' ? `${sessionId}:gemini` : sessionId;
    const cached = this.sessionInfoService.getReviewAnalysisCache(cacheKey);
    logger.info('Cache check', {
      sessionId: sessionId.slice(0, 8),
      provider,
      forceRefresh,
      hasCached: !!cached,
      cachedTurnCount: cached?.turnCount,
      currentTurnCount,
      willUseCache: !forceRefresh && cached && cached.turnCount === currentTurnCount,
    });
    if (!forceRefresh && cached && cached.turnCount === currentTurnCount) {
      logger.info('Returning cached review analysis', {
        sessionId: sessionId.slice(0, 8),
        provider,
        turnCount: currentTurnCount,
        cachedAt: cached.generatedAt,
      });
      // Filter out already-stored recommendations before returning
      const cachedAnalysis = this.normalizeReviewAnalysisPerspective(cached.analysis as ReviewAnalysis);
      const filteredRecommendations = await this.filterStoredRecommendations(
        sessionId,
        cachedAnalysis.recommendations
      );
      return {
        ...cachedAnalysis,
        recommendations: filteredRecommendations,
      };
    }

    // Get metrics from analysis service
    const metricsResult = await this.analysisService.extractMetrics(sessionId);
    const metrics = metricsResult.metrics || {};

    // Get context from cached insights — try all linked IDs since insights may
    // be stored under the conv-* ID or the legacy UUID
    let context = null;
    for (const id of allSessionIds) {
      try {
        const row = this.db.prepare('SELECT context FROM session_insights WHERE session_id = ?').get(id) as { context?: string | null } | undefined;
        if (row?.context) {
          const parsed = parseJson(row.context) as { mission?: string; project?: string; area?: string | null; scope?: string };
          if (parsed.mission && parsed.project) {
            context = { project: parsed.project, area: parsed.area ?? null, mission: parsed.mission, scope: parsed.scope ?? 'feature' };
            break;
          }
        }
      } catch {
        // best-effort
      }
    }

    // Get project path and recent commits to avoid stale recommendations
    let projectPath = await this.historyReader.getConversationWorkingDirectory(sessionId);
    if (!projectPath) {
      // Fall back to conversations table working_directory
      try {
        const { ConversationService } = await import('./conversation-service.js');
        const convService = ConversationService.getInstance();
        const conversation = convService.getConversation(sessionId)
          || convService.getConversationByProviderSession(sessionId)?.conversation;
        if (conversation?.workingDirectory) {
          projectPath = conversation.workingDirectory;
        }
      } catch {
        // Best-effort fallback
      }
    }
    const recentCommits = projectPath ? this.getRecentCommits(projectPath, 24) : [];

    // Get file changes — aggregate across all segment IDs
    const fileChanges = this.getAggregatedFileChanges(allSessionIds);
    const fileChangeSummaries = this.summarizeFileChanges(fileChanges);

    // Get turn evidence from messages — aggregate across all segment IDs
    const allMessages = await this.getAggregatedMessages(allSessionIds);
    const detailedTurnEvidenceSection = this.formatDetailedTurnEvidence(allMessages, turns);

    logger.info('Session review data retrieved', {
      sessionId: sessionId.slice(0, 8),
      isMultiSegment,
      segmentIds: isMultiSegment ? allSessionIds.map(id => id.slice(0, 8)) : undefined,
      totalMessages: allMessages.length,
      turnCount: turns.length,
      projectPath,
      recentCommitCount: recentCommits.length,
      fileChangeCount: fileChanges.length,
      filesChanged: fileChangeSummaries.length,
      hasDetailedTurnEvidence: detailedTurnEvidenceSection.length > 0,
    });

    // Build the shared review data object
    const reviewData = {
      sessionId,
      context,
      turns,
      metrics,
      recentCommits,
      fileChangeSummaries,
      detailedTurnEvidenceSection,
      projectPath: projectPath || undefined,
    };

    // Run LLM analysis using the selected provider
    const llmResult = provider === 'gemini'
      ? await this.runGeminiAnalysis(reviewData)
      : await this.runLLMAnalysis(reviewData);

    // Check if LLM analysis failed (returns default analysis with 'Unknown' goal)
    const llmFailed = llmResult.summary.goal === 'Unknown' &&
                      llmResult.summary.outcome === 'Session analysis unavailable';

    // Format duration - metrics come from extractMetrics which returns camelCase
    const metricsAny = metrics as Record<string, unknown>;
    const durationMin = (metricsAny.durationMinutes as number) || 0;

    const analysis: ReviewAnalysis = {
      summary: llmResult.summary,
      groupedEvents: llmResult.groupedEvents,
      metrics: {
        duration: `${durationMin} min`,
        messages: (metricsAny.messageCount as number) || 0,
        toolUses: (metricsAny.toolUseCount as number) || 0,
        errors: (metricsAny.errorCount as number) || 0,
        filesEdited: (metricsAny.fileEditCount as number) || 0,
      },
      // V4: Skills and guardrails
      skills: llmResult.skills.map((skill, i) => ({
        ...skill,
        id: `${REVIEW_ITEM_ID_PREFIXES.skill}-${sessionId.slice(0, 8)}-${i}`,
      })),
      guardrails: llmResult.guardrails.map((guardrail, i) => ({
        ...guardrail,
        id: `${REVIEW_ITEM_ID_PREFIXES.guardrail}-${sessionId.slice(0, 8)}-${i}`,
      })),
      // Legacy: Keep for backwards compatibility
      recommendations: llmResult.recommendations.map((rec, i) => ({
        ...rec,
        id: `${REVIEW_ITEM_ID_PREFIXES.recommendation}-${sessionId.slice(0, 8)}-${i}`,
      })),
      rootCauses: llmResult.rootCauses || [],
      claudeAnalysis: llmResult.claudeAnalysis || {
        strengths: [],
        weaknesses: [],
        keyInsight: 'Analysis unavailable',
      },
      userFeedback: llmResult.userFeedback || {
        effective: [],
        opportunities: [],
        keyInsight: 'Analysis unavailable',
      },
      projectPath,
      context: context ? { project: context.project, area: context.area ?? null, mission: context.mission } : null,
      reviewProvider: provider,
    };
    const normalizedAnalysis = this.normalizeReviewAnalysisPerspective(analysis);

    // Only cache successful analyses - don't cache failures to allow retries
    if (!llmFailed) {
      this.sessionInfoService.setReviewAnalysisCache(cacheKey, currentTurnCount, normalizedAnalysis);
      logger.info('Cached review analysis', {
        sessionId: sessionId.slice(0, 8),
        provider,
        turnCount: currentTurnCount,
        skillCount: normalizedAnalysis.skills.length,
        guardrailCount: normalizedAnalysis.guardrails.length,
      });
    } else {
      logger.warn('LLM analysis failed, not caching result', {
        sessionId: sessionId.slice(0, 8),
        turnCount: currentTurnCount,
      });
    }

    // Filter out already-stored recommendations before returning
    const filteredRecommendations = await this.filterStoredRecommendations(
      sessionId,
      normalizedAnalysis.recommendations
    );

    getEventJournal().record({
      event: llmFailed ? 'review.failed' : 'review.completed',
      severity: llmFailed ? 'warn' : 'info',
      component: 'SessionReviewService',
      sessionId,
      fields: {
        provider,
        turnCount: currentTurnCount,
        recommendationCount: filteredRecommendations.length,
      },
    });

    return {
      ...normalizedAnalysis,
      recommendations: filteredRecommendations,
    };
  }

  private buildReviewPrompt(data: ReviewData): string {
    const mission = data.context?.mission || 'Unknown goal';
    const project = data.context?.project || 'Unknown project';
    const turnsStr = this.formatTurnsForPrompt(data.turns);
    const fileChangesSection = this.formatFileChangesForPrompt(data.fileChangeSummaries || []);
    const frictionTurns = data.turns.filter(t =>
      ['friction', 'pivot', 'debug', 'fix'].includes(t.tag) || t.incomplete
    );
    const frictionContext = this.formatFrictionTurnsForPrompt(frictionTurns);
    const existingKnowledge = this.gatherExistingKnowledge(data.projectPath);

    return `You are a session reviewer for Lattice, a tool that helps developers work more effectively with AI coding agents. Your job is to extract maximum value from a completed session.

## Session Context
- **Project:** ${project}
- **Mission:** ${mission}

## Session Turns
Each entry = one user request + assistant response:

${turnsStr}

${data.detailedTurnEvidenceSection || ''}

## Stats
- ${String(data.metrics.messageCount ?? '?')} messages, ${String(data.metrics.toolUseCount ?? '?')} tool uses, ${String(data.metrics.errorCount ?? '?')} errors
- ${String(data.metrics.fileEditCount ?? '?')} files modified over ${String(data.metrics.durationMinutes ?? '?')} minutes
${fileChangesSection}${frictionContext}${data.recentCommits && data.recentCommits.length > 0 ? `
## Recent Commits (Last 24 Hours)
These commits were made to this project recently (possibly by other sessions or manual work). **DO NOT recommend something that was already fixed by one of these commits.**

${data.recentCommits.map(c => `- ${c}`).join('\n')}

**CRITICAL**: If a commit message suggests a fix was made (e.g., "fix loading spinner", "separate button states"), DO NOT recommend that same fix. The problem has already been resolved.
` : ''}${existingKnowledge}
## What You're Producing

Lattice helps developers work better with AI agents. Each session review should make the NEXT session better. The core question: **"What should be different next time?"**

**Critical framing rule:** Write for someone reading this review A DAY LATER who doesn't remember session details. No function names, no "Turn 7 found X", no internal jargon. Describe PROBLEMS and SOLUTIONS in plain language that stands alone.

**Perspective and actor clarity rules (MUST follow):**
- This session is one user directing one AI assistant (Claude or Codex).
- Never refer to actors as "the team", "we", "our team", "developers", or "engineers."
- Use explicit actors: "the user", "the assistant", "Claude", "Codex", or "the user and assistant."
- Bad: "the team pivoted after errors." Good: "the user and assistant pivoted after repeated errors."

### 1. Summary
- **goal**: What the session set out to do
- **outcome**: What actually happened, including pivots

### 2. Recap
A concise prose paragraph (2-4 sentences) describing what happened in this session chronologically. Not a list — flowing narrative. Think "commit message for the whole session." Keep it brief and high-level.

### 3. Highlights
3-5 notable moments — friction, key decisions, pivots, breakthroughs. Short phrases, not sentences. Plain language — no function names or internal jargon. A reader who wasn't in the session should understand.

### 4. Improvements
Things that would make the NEXT session on this project better. Each goes on a backlog.

**IMPORTANT: Most sessions should produce ZERO improvements.** Before suggesting ANY improvement, ask yourself:
- Did the session have genuine friction that will RECUR? If it was a one-off debugging cycle that got resolved, that's just work — not an improvement.
- Is the improvement something the developer wouldn't think of on their own? "Write tests for the thing you built" is obvious. "The tooltip component's positioning model is fundamentally fragile" is insight.
- Would you bet money the developer will accept this? If you're unsure, leave it out.

Sessions that typically produce zero improvements:
- Strategy/design discussions (the value was in the decisions made)
- Clean execution of a defined plan (the work went smoothly)
- Small focused tasks completed without friction
- Sessions where the built artifact IS the improvement (e.g., building a test suite)

Only include an improvement when you've identified friction that (a) will recur, (b) has a clear action, and (c) the developer wouldn't address on their own. Empty improvements array is the DEFAULT, not the exception.

**Every improvement is an argument with three parts:**
- **friction**: What went wrong or was harder than it needed to be? Be specific about what you observed in THIS session — "spent 3 turns debugging tooltip positioning in different contexts" not "tooltips could be improved."
- **action**: What specifically should be done? Concrete enough that someone could start working on it.
- **rationale**: Why does this action address this friction? This is the connective tissue — explain the causal link. "The tooltip component uses hardcoded offsets per-instance instead of computing position relative to the anchor, which is why each new context requires a separate fix."

If you can't make all three parts of this argument convincingly, don't include the improvement.

**Every improvement also has a type (shape) and scope:**

#### Types

**\`skill\`** — A Claude Code skill (SKILL.md file that creates a /slash-command).

Skills are an extension mechanism, not just checklists. They come in two forms:
- **Reference skills**: Domain knowledge or conventions Claude applies to current work (e.g., /api-conventions injects API design patterns whenever relevant)
- **Task skills**: Step-by-step workflows for specific actions (e.g., /deploy runs a deployment pipeline)

Good skills have at least one of these power features:
- **Scripts or tooling** that do mechanical work Claude shouldn't do ad-hoc (scanning, generating, validating)
- **Dynamic context injection** (\`!\`command\`\`) that pulls live data before Claude sees the prompt
- **Tool restrictions** that create safe execution modes (read-only exploration, sandboxed execution)
- **Subagent execution** (\`context: fork\`) for isolated research or analysis tasks
- **Templates or reference files** that standardize output format

Also include: \`name\` (slash-command name), \`steps\` (the workflow)

Skill quality gate — ask yourself ALL of these:
1. Would someone reach for this skill WITHOUT having done this session? If it only makes sense because of what just happened, it's not a skill — it's just the work.
2. Does it encode reusable JUDGMENT or PROCESS, not just "the steps I took"? If the value was in the specific decisions made during the session, a checklist can't capture that.
3. Is it meaningfully better than just asking Claude to do it? A skill that says "search for X, then check Y, then summarize" is just a prompt — not a skill. It needs scripts, templates, dynamic context, or tool restrictions to justify its existence.
4. The name should be general-purpose (e.g., \`/test-matrix\`, \`/compare-outputs\`), NOT session-specific (\`/review-prompt-experiment\`)

**\`guardrail\`** — Automation that prevents a class of problem before it happens (lint rule, git hook, CI check, runtime validation).
Also include: \`name\`

Describe the PROTECTION BOUNDARY, not the implementation details. "Prevent ungated Pro endpoints from shipping" not "add integration test that seeds database with 50 test sessions and asserts getActiveSessions excludes..." The implementation is for the developer to figure out.

Guardrail quality gate:
1. Does this protect against a RECURRING class of problem, not just the specific bug from this session?
2. Is this a genuine tooling/infrastructure gap, or just "write a regression test for what you fixed"? Writing tests for bugs you fix is normal development — it's not a recommendation. A guardrail protects against a class of problem the developer wouldn't naturally test for.
3. Would this be worth maintaining? Lint rules and hooks have ongoing cost. The problem class should be frequent enough to justify it.

**\`codebase\`** — A concrete code change where the problem AND the solution are both clear.
Also include: \`title\`

Examples: "Add requirePro middleware to Express router", "Extract shared tooltip component with portal-based positioning", "Add semantic similarity to recommendation dedup." The fix is known and specific.

**Codebase vs investigation — the deciding question:** Can you confidently describe the exact change to make? If your action uses words like "investigate", "explore whether", "figure out", or "the right approach isn't clear" — that's an investigation, not a codebase change. Don't dress up uncertainty as a concrete recommendation.

**\`investigation\`** — The friction pattern is clear but the right fix isn't obvious yet. Something needs deeper analysis before committing to a solution.
Also include: \`title\`

This is for when you can clearly diagnose a pattern of friction but prescribing a specific fix would be guessing. Examples: "Tooltip positioning breaks in every new UI context — investigate whether the component needs a portal/floating-UI approach or if the offset model is fundamentally wrong." "Multiple sessions modifying the same branch causes workspace collisions — explore locking vs notification vs worktree isolation approaches." The value is in clearly articulating the problem and pointing at where to look, NOT in guessing at a solution.

**\`workflow\`** — Knowledge that should persist in CLAUDE.md or project documentation so future sessions benefit.
Also include: \`title\`

Examples: "Font loading requires changes in two places (HTML link + CSS class)", "npm automation tokens don't require OTP", "When doing large renames, build a checklist of all identifier patterns first." These are lessons learned that would save time in future sessions if the agent knew them upfront.

Workflow quality gate: Would an AI agent starting a fresh session on this project benefit from knowing this? If it's too specific to this one situation, skip it.

#### Scope

Every improvement must declare its scope:
- **\`project\`** — Applies to this project only (project CLAUDE.md, project skills, project code). This is the default and should be used for most improvements.
- **\`global\`** — Applies across all projects (personal skills, global CLAUDE.md, general workflow patterns). Use ONLY when the friction is clearly not project-specific. Bias heavily toward \`project\` — global recommendations need strong justification.

#### What is NOT an improvement
- "Remember to always X" — advice without automation or documentation
- Anything only relevant to this session's specific problem that won't recur
- Generic best practices the user already knows
- Work that was ALREADY COMPLETED in this session — if the session built it, don't suggest building it again
- Tooling that was created as part of the session's work
- "Write a regression test for the bug you just fixed" — that's finishing the work, not an improvement
- Documenting what the session just built — "the test suite requires compiled assets" is something the developer just learned by building it
- Noting an unresolved design question as a "codebase" recommendation — if the session intentionally left a decision open, that's not a recommendation
- "Audit X for correctness" when the session already did the audit — don't recommend the work that was just completed
- Claude getting confused about project context — that's not fixable with a recommendation

**The bar: would you bet money the developer accepts this?** If you're padding to avoid returning empty, stop. Empty is correct for most sessions.

---

Return JSON:
{
  "summary": { "goal": "...", "outcome": "..." },
  "recap": "Prose paragraph describing what happened chronologically.",
  "highlights": ["Short phrase", "..."],
  "improvements": [
    {
      "type": "skill",
      "scope": "project",
      "name": "slash-command-name",
      "friction": "What went wrong or was harder than needed",
      "action": "What this skill does and how it helps",
      "rationale": "Why a skill specifically addresses this friction",
      "steps": ["Step 1", "Step 2"]
    },
    {
      "type": "guardrail",
      "scope": "project",
      "name": "kebab-case-name (e.g. pro-endpoint-gate, branch-content-check)",
      "friction": "What class of problem recurred",
      "action": "What protection boundary to establish",
      "rationale": "Why this prevents the friction from recurring"
    },
    {
      "type": "codebase",
      "scope": "project",
      "title": "Short descriptive name",
      "friction": "What went wrong or was harder than needed",
      "action": "What specific code change to make",
      "rationale": "Why this change addresses the friction"
    },
    {
      "type": "investigation",
      "scope": "project",
      "title": "Short descriptive name",
      "friction": "What friction pattern was observed",
      "action": "What to investigate and where to look",
      "rationale": "Why we can't prescribe a fix yet and what we need to learn"
    },
    {
      "type": "workflow",
      "scope": "project",
      "title": "Short descriptive name",
      "friction": "What knowledge gap caused friction",
      "action": "What to document and where",
      "rationale": "Why future sessions would benefit from knowing this"
    }
  ]
}

Empty arrays are fine. Never pad.`;
  }

  /**
   * Map review output (highlights + typed improvements) to the ReviewResult shape
   * expected by the rest of the system (skills, guardrails, recommendations, etc.)
   */
  private mapReviewOutputToResult(parsed: {
    summary: { goal: string; outcome: string };
    recap?: string | string[];
    highlights?: string[];
    improvements?: Array<Record<string, unknown>>;
  }): ReviewResult {
    const improvements = parsed.improvements || [];
    const summary = {
      goal: this.normalizePerspectiveText(parsed.summary.goal),
      outcome: this.normalizePerspectiveText(parsed.summary.outcome),
    };
    const recapTextRaw = Array.isArray(parsed.recap) ? parsed.recap.join(' ') : (parsed.recap || '');
    const recapText = this.normalizePerspectiveText(recapTextRaw);
    const highlights = (parsed.highlights || []).map(h => this.normalizePerspectiveText(h));

    // Pack friction/action/rationale into existing fields using \n---\n separator.
    // Card components split on this to render labeled sections.
    // Also supports legacy what/why/when fields from cached reviews.
    const packFAR = (i: Record<string, unknown>) => {
      const f = this.normalizePerspectiveText(String(i.friction || i.what || ''));
      const a = this.normalizePerspectiveText(String(i.action || i.why || ''));
      const r = this.normalizePerspectiveText(String(i.rationale || i.when || ''));
      return [f, a, r].join('\n---\n');
    };

    const skills: Omit<Skill, 'id'>[] = improvements
      .filter(i => i.type === 'skill')
      .map(i => ({
        name: String(i.name || 'unnamed-skill'),
        description: packFAR(i),
        instructions: Array.isArray(i.steps) ? (i.steps as string[]).map((s, idx) => `${idx + 1}. ${s}`).join('\n') : String(i.steps || ''),
        hasScript: false,
      }));

    const guardrails: Omit<Guardrail, 'id'>[] = improvements
      .filter(i => i.type === 'guardrail')
      .map(i => {
        // Derive a name from friction text if model omits name field
        let name = String(i.name || '').trim();
        if (!name) {
          const friction = String(i.friction || i.action || '');
          // Take first ~6 words, kebab-case them
          name = friction.split(/\s+/).slice(0, 6).join('-').toLowerCase()
            .replace(/[^a-z0-9-]/g, '').replace(/-+/g, '-').replace(/^-|-$/g, '')
            || 'guardrail';
        }
        return {
          type: name,
          prevents: packFAR(i),
          implementation: '',
        };
      });

    // Map codebase, investigation, and workflow types to recommendations.
    // Scope determines target: global → global_instructions, project → codebase or project_instructions.
    const targetForImprovement = (i: Record<string, unknown>): 'codebase' | 'project_instructions' | 'global_instructions' => {
      const scope = String(i.scope || 'project');
      if (scope === 'global') return 'global_instructions';
      if (i.type === 'workflow') return 'project_instructions';
      return 'codebase';
    };

    const recommendations: Omit<ReviewAnalysis['recommendations'][0], 'id'>[] = improvements
      .filter(i => i.type === 'codebase' || i.type === 'investigation' || i.type === 'workflow')
      .map(i => ({
        target: targetForImprovement(i),
        improvementType: String(i.type) as 'codebase' | 'investigation' | 'workflow',
        action: String(i.title || ''),
        friction: packFAR(i),
        rationale: '',
      }));

    return {
      summary,
      groupedEvents: {
        friction: [],
        built: recapText ? [{ text: recapText, icon: '' }] : [],
        learned: highlights.map(h => ({ text: h, icon: '' })),
      },
      skills,
      guardrails,
      recommendations,
      rootCauses: [],
      claudeAnalysis: { strengths: [], weaknesses: [], keyInsight: '' },
      userFeedback: { effective: [], opportunities: [], keyInsight: '' },
    };
  }

  private normalizePerspectiveText(text: string): string {
    return text
      .replace(/\bthe team\b/gi, 'the user and assistant')
      .replace(/\bour team\b/gi, 'the user and assistant')
      .replace(/\bthis team\b/gi, 'this user-assistant session')
      .replace(/\bwe should\b/gi, 'the next session should')
      .replace(/\bwe need to\b/gi, 'the next session should');
  }

  private normalizeReviewAnalysisPerspective(analysis: ReviewAnalysis): ReviewAnalysis {
    return {
      ...analysis,
      summary: {
        goal: this.normalizePerspectiveText(analysis.summary.goal),
        outcome: this.normalizePerspectiveText(analysis.summary.outcome),
      },
      groupedEvents: {
        friction: analysis.groupedEvents.friction.map(event => ({
          ...event,
          text: this.normalizePerspectiveText(event.text),
        })),
        built: analysis.groupedEvents.built.map(event => ({
          ...event,
          text: this.normalizePerspectiveText(event.text),
        })),
        learned: analysis.groupedEvents.learned.map(event => ({
          ...event,
          text: this.normalizePerspectiveText(event.text),
        })),
      },
      skills: analysis.skills.map(skill => ({
        ...skill,
        description: this.normalizePerspectiveText(skill.description),
        instructions: this.normalizePerspectiveText(skill.instructions),
      })),
      guardrails: analysis.guardrails.map(guardrail => ({
        ...guardrail,
        prevents: this.normalizePerspectiveText(guardrail.prevents),
        implementation: this.normalizePerspectiveText(guardrail.implementation),
      })),
      recommendations: analysis.recommendations.map(recommendation => ({
        ...recommendation,
        friction: this.normalizePerspectiveText(recommendation.friction),
        action: this.normalizePerspectiveText(recommendation.action),
        rationale: this.normalizePerspectiveText(recommendation.rationale),
      })),
      rootCauses: analysis.rootCauses.map(rootCause => ({
        surface: this.normalizePerspectiveText(rootCause.surface),
        root: this.normalizePerspectiveText(rootCause.root),
        preventable: this.normalizePerspectiveText(rootCause.preventable),
      })),
      claudeAnalysis: {
        strengths: analysis.claudeAnalysis.strengths.map(item => this.normalizePerspectiveText(item)),
        weaknesses: analysis.claudeAnalysis.weaknesses.map(item => this.normalizePerspectiveText(item)),
        keyInsight: this.normalizePerspectiveText(analysis.claudeAnalysis.keyInsight),
      },
      userFeedback: {
        effective: analysis.userFeedback.effective.map(item => this.normalizePerspectiveText(item)),
        opportunities: analysis.userFeedback.opportunities.map(item => this.normalizePerspectiveText(item)),
        keyInsight: this.normalizePerspectiveText(analysis.userFeedback.keyInsight),
      },
    };
  }

  private async runLLMAnalysis(data: ReviewData): Promise<ReviewResult> {
    // Gated at the generation step, not at analyzeForReview — a stored review
    // must still be readable when the switch is off.
    if (!allowGeneration('sessionReview')) {
      throw new Error(`Session review generation is off — set generation.sessionReview to true in ${CONFIG_FILE}`);
    }
    const client = this.getClient();

    logger.info('Session review input data', {
      provider: 'opus',
      context: data.context,
      turnCount: data.turns.length,
      metrics: data.metrics,
    });

    const prompt = this.buildReviewPrompt(data);
    logger.debug('Session review prompt', { promptLength: prompt.length });

    const startTime = Date.now();
    try {
      const response = await client.messages.create({
        model: REVIEW_MODEL,
        max_tokens: 4000,
        thinking: REVIEW_THINKING,
        messages: [{ role: 'user', content: prompt }],
      });

      const durationMs = Date.now() - startTime;

      // Log cost for SESSION_REVIEW operation
      try {
        const costTracker = getCostTracker();
        costTracker.log({
          sessionId: data.sessionId,
          operation: 'SESSION_REVIEW',
          ...backgroundProvenance(response, REVIEW_MODEL),
          inputTokens: response.usage?.input_tokens || 0,
          outputTokens: response.usage?.output_tokens || 0,
          cacheCreationInputTokens: response.usage?.cache_creation_input_tokens || 0,
          cacheReadInputTokens: response.usage?.cache_read_input_tokens || 0,
          durationMs,
        });
      } catch (costErr) {
        logger.debug('Failed to log review cost', { error: costErr });
      }

      const text = response.content[0].type === 'text' ? response.content[0].text : '';
      const stopReason = response.stop_reason;

      // Log the raw response
      logger.info('Session review LLM response', {
        textLength: text.length,
        stopReason,
        durationMs,
      });

      // Warn if response was truncated
      if (stopReason === 'max_tokens') {
        logger.warn('LLM response truncated (hit max_tokens)', { textLength: text.length });
      }

      const jsonMatch = text.match(/\{[\s\S]*\}/);

      if (!jsonMatch) {
        logger.error('No JSON in LLM response', { text: text.slice(0, 200) });
        return this.getDefaultAnalysis();
      }

      let jsonStr = jsonMatch[0];

      // Attempt to repair common JSON issues
      jsonStr = this.repairJson(jsonStr);

      const parsed = parseJson(jsonStr) as {
        summary: { goal: string; outcome: string };
        recap?: string | string[];
        highlights?: string[];
        improvements?: Array<Record<string, unknown>>;
      };

      const result = this.mapReviewOutputToResult(parsed);

      logger.info('Session review parsed result', {
        highlights: parsed.highlights?.length ?? 0,
        improvements: parsed.improvements?.length ?? 0,
        skills: result.skills.length,
        guardrails: result.guardrails.length,
        recommendations: result.recommendations.length,
      });

      return result;
    } catch (err) {
      logger.error('LLM analysis failed', { error: err instanceof Error ? err.message : String(err) });
      return this.getDefaultAnalysis();
    }
  }

  /**
   * Run review analysis using Gemini 3.1 Pro instead of Opus.
   * Uses the exact same prompt and expects the same JSON schema.
   */
  private async runGeminiAnalysis(data: ReviewData): Promise<ReviewResult> {
    if (!allowGeneration('sessionReview')) {
      throw new Error(`Session review generation is off — set generation.sessionReview to true in ${CONFIG_FILE}`);
    }
    if (!geminiService.isConsultationAvailable()) {
      throw new Error(`Gemini API key not configured — set gemini.apiKey in ${CONFIG_FILE}`);
    }

    logger.info('Session review input data', {
      provider: 'gemini',
      context: data.context,
      turnCount: data.turns.length,
      metrics: data.metrics,
    });

    const prompt = this.buildReviewPrompt(data);
    logger.info('Session review prompt (Gemini)', { promptLength: prompt.length });

    const startTime = Date.now();
    try {
      const result = await geminiService.consultSessionRaw(prompt, {
        responseMimeType: 'application/json',
        temperature: 0.3,
        maxOutputTokens: 4096,
      });

      const durationMs = Date.now() - startTime;

      // Log cost
      try {
        const costTracker = getCostTracker();
        costTracker.log({
          sessionId: data.sessionId,
          operation: 'SESSION_REVIEW',
          model: 'gemini-3.1-pro-preview',
          inputTokens: result.tokens.input,
          // Gemini bills thinking as output. No cache fields: this path does
          // not use context caching, and Gemini reports it differently anyway.
          outputTokens: result.tokens.output + result.tokens.thinking,
          durationMs,
          provider: 'google',
        });
      } catch (costErr) {
        logger.debug('Failed to log Gemini review cost', { error: costErr });
      }

      logger.info('Session review Gemini response', {
        textLength: result.response.length,
        durationMs,
        tokens: result.tokens,
        estimatedCost: result.estimatedCostUsd,
      });

      const parsed = parseJson(result.response) as {
        summary: { goal: string; outcome: string };
        recap?: string | string[];
        highlights?: string[];
        improvements?: Array<Record<string, unknown>>;
      };

      const mappedResult = this.mapReviewOutputToResult(parsed);

      logger.info('Session review Gemini parsed result', {
        highlights: parsed.highlights?.length ?? 0,
        improvements: parsed.improvements?.length ?? 0,
        skills: mappedResult.skills.length,
        guardrails: mappedResult.guardrails.length,
        recommendations: mappedResult.recommendations.length,
      });

      return mappedResult;
    } catch (err) {
      logger.error('Gemini analysis failed', { error: err instanceof Error ? err.message : String(err) });
      return this.getDefaultAnalysis();
    }
  }

  /**
   * Attempt to repair malformed JSON from LLM responses.
   * Common issues: trailing commas, unclosed brackets, unescaped quotes in strings.
   */
  private repairJson(jsonStr: string): string {
    let repaired = jsonStr;

    // Remove trailing commas before } or ]
    repaired = repaired.replace(/,\s*([}\]])/g, '$1');

    // Try to balance brackets if truncated
    const openBraces = (repaired.match(/\{/g) || []).length;
    const closeBraces = (repaired.match(/\}/g) || []).length;
    const openBrackets = (repaired.match(/\[/g) || []).length;
    const closeBrackets = (repaired.match(/\]/g) || []).length;

    // If we have unclosed structures, try to close them
    if (openBraces > closeBraces || openBrackets > closeBrackets) {
      logger.info('Attempting to repair truncated JSON', {
        openBraces,
        closeBraces,
        openBrackets,
        closeBrackets,
      });

      // Remove any trailing partial content (incomplete string or key)
      // Look for the last complete value
      const lastCompletePattern = /("[^"]*"|\d+|true|false|null|\}|\])\s*[,}}\]]*\s*$/;
      const match = repaired.match(lastCompletePattern);
      if (match) {
        const lastGoodPos = repaired.lastIndexOf(match[0]) + match[0].length;
        repaired = repaired.slice(0, lastGoodPos);
      }

      // Add missing closing brackets
      for (let i = 0; i < openBrackets - closeBrackets; i++) {
        repaired += ']';
      }
      for (let i = 0; i < openBraces - closeBraces; i++) {
        repaired += '}';
      }
    }

    return repaired;
  }

  private getDefaultAnalysis(): {
    summary: ReviewAnalysis['summary'];
    groupedEvents: ReviewAnalysis['groupedEvents'];
    skills: Omit<Skill, 'id'>[];
    guardrails: Omit<Guardrail, 'id'>[];
    recommendations: Omit<ReviewAnalysis['recommendations'][0], 'id'>[];
    rootCauses: ReviewAnalysis['rootCauses'];
    claudeAnalysis: ReviewAnalysis['claudeAnalysis'];
    userFeedback: ReviewAnalysis['userFeedback'];
  } {
    return {
      summary: {
        goal: 'Unknown',
        outcome: 'Session analysis unavailable',
      },
      groupedEvents: {
        friction: [],
        built: [],
        learned: [{ text: 'Session analysis unavailable', icon: '❓' }],
      },
      skills: [],
      guardrails: [],
      recommendations: [],
      rootCauses: [],
      claudeAnalysis: {
        strengths: [],
        weaknesses: [],
        keyInsight: 'Analysis unavailable',
      },
      userFeedback: {
        effective: [],
        opportunities: [],
        keyInsight: 'Analysis unavailable',
      },
    };
  }

  /**
   * Filter out recommendations that have already been stored (accepted or dismissed)
   * for this session. This prevents showing the same recommendations repeatedly.
   *
   * Uses both ID matching (for cached analysis) and semantic similarity matching
   * (for when LLM regenerates with slightly different wording).
   */
  private async filterStoredRecommendations(
    sessionId: string,
    recommendations: ReviewAnalysis['recommendations']
  ): Promise<ReviewAnalysis['recommendations']> {
    if (recommendations.length === 0) return recommendations;

    try {
      // Get all stored recommendations for this session (any status)
      const storedRecs = await this.getRecommendationsForSession(sessionId);

      if (storedRecs.length === 0) return recommendations;

      // Build a set of stored recommendation IDs for quick lookup
      const storedIds = new Set(storedRecs.map(r => r.id));

      const filtered = recommendations.filter(rec => {
        // First check exact ID match
        if (storedIds.has(rec.id)) {
          return false;
        }

        // Then check semantic similarity against all stored recommendations
        for (const stored of storedRecs) {
          if (this.areRecommendationsSimilar(rec, stored)) {
            logger.info('Filtered semantically similar recommendation', {
              sessionId: sessionId.slice(0, 8),
              newRecId: rec.id,
              matchedStoredId: stored.id,
              newAction: rec.action.slice(0, 80),
              storedAction: stored.action.slice(0, 80),
            });
            return false;
          }
        }

        return true;
      });

      const removedCount = recommendations.length - filtered.length;
      if (removedCount > 0) {
        logger.info('Filtered already-stored recommendations', {
          sessionId: sessionId.slice(0, 8),
          original: recommendations.length,
          filtered: filtered.length,
          removed: removedCount,
        });
      }

      return filtered;
    } catch (err) {
      logger.warn('Failed to filter stored recommendations, returning all', {
        error: err instanceof Error ? err.message : String(err),
      });
      return recommendations;
    }
  }

  /**
   * Check if two recommendations are semantically similar using Jaccard similarity
   * on the action and friction text.
   */
  private areRecommendationsSimilar(
    newRec: ReviewAnalysis['recommendations'][0],
    stored: { action: string; friction: string; target: string }
  ): boolean {
    // Must be same target type
    if (newRec.target !== stored.target) {
      return false;
    }

    // Compute Jaccard similarity on action text (primary comparison)
    const actionSimilarity = this.jaccardSimilarity(
      this.tokenize(newRec.action),
      this.tokenize(stored.action)
    );

    // Compute Jaccard similarity on friction text (secondary)
    const frictionSimilarity = this.jaccardSimilarity(
      this.tokenize(newRec.friction),
      this.tokenize(stored.friction)
    );

    // Weight action more heavily since it's the specific change being made
    const combinedSimilarity = actionSimilarity * 0.7 + frictionSimilarity * 0.3;

    // Threshold: 0.5 means at least half the meaningful words overlap
    const SIMILARITY_THRESHOLD = 0.5;

    return combinedSimilarity >= SIMILARITY_THRESHOLD;
  }

  /**
   * Tokenize text into normalized words for comparison.
   * Removes common stop words and normalizes to lowercase.
   */
  private tokenize(text: string): Set<string> {
    const stopWords = new Set([
      'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
      'of', 'with', 'by', 'from', 'as', 'is', 'was', 'are', 'were', 'been',
      'be', 'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would',
      'could', 'should', 'may', 'might', 'must', 'shall', 'can', 'need',
      'that', 'this', 'these', 'those', 'it', 'its', 'when', 'where', 'how',
      'which', 'who', 'whom', 'what', 'if', 'then', 'than', 'so', 'just',
    ]);

    const words = text
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, ' ')  // Replace non-alphanumeric with spaces
      .split(/\s+/)
      .filter(word => word.length > 2 && !stopWords.has(word));

    return new Set(words);
  }

  /**
   * Compute Jaccard similarity between two sets.
   * Returns value between 0 (no overlap) and 1 (identical).
   */
  private jaccardSimilarity(set1: Set<string>, set2: Set<string>): number {
    if (set1.size === 0 && set2.size === 0) return 1;
    if (set1.size === 0 || set2.size === 0) return 0;

    let intersection = 0;
    for (const item of set1) {
      if (set2.has(item)) intersection++;
    }

    const union = set1.size + set2.size - intersection;
    return intersection / union;
  }

  // =============================================================================
  // Multi-segment aggregation helpers
  // =============================================================================

  /**
   * Resolve all linked session IDs for a unified conversation.
   * Given any session ID (conv-* or UUID), returns the full set of IDs that
   * may contain data: the conversation ID itself + all segment provider session IDs.
   * Falls back to [sessionId] for legacy sessions without a conversation record.
   */
  private async resolveAllLinkedSessionIds(sessionId: string): Promise<string[]> {
    try {
      const { ConversationService } = await import('./conversation-service.js');
      const convService = ConversationService.getInstance();

      // Try direct lookup (works if sessionId is a conv-* ID)
      let conversation = convService.getConversation(sessionId);

      // If not found, try reverse lookup (sessionId is a provider UUID)
      if (!conversation) {
        const result = convService.getConversationByProviderSession(sessionId);
        if (result) {
          conversation = result.conversation;
        }
      }

      if (!conversation) {
        return [sessionId];
      }

      // Collect all unique IDs: the conv-* ID + all segment provider session IDs
      const ids = new Set<string>();
      ids.add(conversation.conversationId);
      for (const segment of conversation.segments) {
        if (segment.providerSessionId) {
          ids.add(segment.providerSessionId);
        }
      }
      // Also include the original input ID in case it's not in the segments
      ids.add(sessionId);

      return Array.from(ids);
    } catch (error) {
      logger.warn('Failed to resolve linked session IDs, falling back to single ID', {
        sessionId: sessionId.slice(0, 8),
        error: error instanceof Error ? error.message : String(error),
      });
      return [sessionId];
    }
  }

  /**
   * Aggregate turns across all linked session IDs, deduplicate by turn number.
   */
  private async getAggregatedTurns(allSessionIds: string[]): Promise<Turn[]> {
    const turnMap = new Map<number, Turn>();
    for (const id of allSessionIds) {
      const turns = await this.turnCaptureService.getTurnsForSession(id);
      for (const turn of turns) {
        // Keep the first occurrence of each turn number (earlier segment wins)
        if (!turnMap.has(turn.turnNumber)) {
          turnMap.set(turn.turnNumber, turn);
        }
      }
    }
    return Array.from(turnMap.values()).sort((a, b) => a.turnNumber - b.turnNumber);
  }

  /**
   * Aggregate file changes across all linked session IDs, deduplicate by change ID.
   */
  private getAggregatedFileChanges(allSessionIds: string[]): FileChange[] {
    const changeMap = new Map<string, FileChange>();
    for (const id of allSessionIds) {
      const changes = this.sessionInfoService.getFileChanges(id);
      for (const change of changes) {
        if (!changeMap.has(change.id)) {
          changeMap.set(change.id, {
            sessionId: change.sessionId,
            turnNumber: change.turnNumber,
            toolName: change.toolName,
            filePath: change.filePath,
            oldString: change.oldString,
            newString: change.newString,
          });
        }
      }
    }
    return Array.from(changeMap.values()).sort((a, b) => a.turnNumber - b.turnNumber);
  }

  /**
   * Aggregate messages across all linked session IDs, deduplicate by message ID, sort by timestamp.
   */
  private async getAggregatedMessages(allSessionIds: string[]): Promise<UnifiedMessage[]> {
    const messageMap = new Map<string, UnifiedMessage>();
    for (const id of allSessionIds) {
      const messages = readMessages(id);
      for (const msg of messages) {
        if (!messageMap.has(msg.id)) {
          messageMap.set(msg.id, msg);
        }
      }
    }
    return Array.from(messageMap.values()).sort((a, b) =>
      new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
    );
  }

  /**
   * Format detailed turn evidence from pre-aggregated messages.
   * This variant accepts messages directly (already aggregated across segments)
   * instead of fetching from a single sessionId.
   */
  private formatDetailedTurnEvidence(messages: UnifiedMessage[], turns: Turn[]): string {
    if (turns.length === 0 || messages.length === 0) {
      return '';
    }

    try {
      const details = this.extractDetailedTurnEvidence(messages);
      if (details.length === 0) {
        return '';
      }

      const turnMap = new Map(turns.map(turn => [turn.turnNumber, turn]));
      const detailMap = new Map(details.map(detail => [detail.turnNumber, detail]));
      const criticalTurnNumbers = turns
        .filter(turn => ['friction', 'pivot', 'debug', 'fix'].includes(turn.tag) || turn.incomplete)
        .map(turn => turn.turnNumber)
        .sort((a, b) => b - a);
      const recentTurnNumbers = turns.slice(-8).map(turn => turn.turnNumber).reverse();

      const selected: number[] = [];
      const seen = new Set<number>();
      const addTurn = (turnNumber: number): void => {
        if (seen.has(turnNumber)) return;
        seen.add(turnNumber);
        selected.push(turnNumber);
      };

      for (const turnNumber of criticalTurnNumbers) {
        if (selected.length >= 6) break;
        addTurn(turnNumber);
      }
      for (const turnNumber of recentTurnNumbers) {
        if (selected.length >= 12) break;
        addTurn(turnNumber);
      }
      if (turns.length > 0 && selected.length < 12) {
        addTurn(1);
      }

      const sortedSelected = selected.sort((a, b) => a - b);
      const lines = [
        '## Turn Evidence (selected excerpts)',
        'Use these direct turn excerpts as grounding evidence when writing the analysis:',
        '',
      ];

      for (const turnNumber of sortedSelected) {
        const turn = turnMap.get(turnNumber);
        const detail = detailMap.get(turnNumber);
        if (!turn || !detail) continue;

        const status = turn.incomplete ? `, interrupted (${turn.terminationReason})` : '';
        lines.push(`### Turn ${turnNumber} [${turn.tag}] (${turn.toolCount} tools${status})`);
        lines.push(`User: ${detail.userMessage || '(no user text captured)'}`);
        lines.push(`Assistant: ${detail.assistantResponse || '(no assistant text captured)'}`);
        if (detail.tools.length > 0) {
          lines.push(`Tools: ${detail.tools.slice(0, 6).join(' | ')}`);
        } else {
          lines.push('Tools: none');
        }
        lines.push('');
      }

      return lines.join('\n');
    } catch (error) {
      logger.warn('Failed to build detailed turn evidence for review prompt', {
        error: error instanceof Error ? error.message : String(error),
      });
      return '';
    }
  }

  // =============================================================================
  // Prompt formatting helpers
  // =============================================================================

  /**
   * Format turn summaries as a compact turn-by-turn timeline for prompt input.
   */
  private formatTurnsForPrompt(turns: Turn[]): string {
    if (turns.length === 0) {
      return 'No turns captured';
    }

    return turns.map(turn => {
      const completion = turn.incomplete ? `${turn.terminationReason}` : 'completed';
      const actions = turn.actions.length > 0
        ? turn.actions.map(action => `  - ${action}`).join('\n')
        : '  - (no action summary)';
      return [
        `Turn ${turn.turnNumber} ${turn.icon} [${turn.tag}] (${turn.toolCount} tools, ${completion})`,
        `  - ${turn.headline}`,
        actions,
      ].join('\n');
    }).join('\n\n');
  }

  /**
   * Pull concise message excerpts for selected turns from the unified message store.
   * This gives the LLM direct turn evidence instead of only relying on turn headlines.
   */
  private async formatDetailedTurnEvidenceForPrompt(sessionId: string, turns: Turn[]): Promise<string> {
    if (turns.length === 0) {
      return '';
    }

    try {
      const messages = readMessages(sessionId);
      if (messages.length === 0) {
        return '';
      }

      const details = this.extractDetailedTurnEvidence(messages);
      if (details.length === 0) {
        return '';
      }

      const turnMap = new Map(turns.map(turn => [turn.turnNumber, turn]));
      const detailMap = new Map(details.map(detail => [detail.turnNumber, detail]));
      const criticalTurnNumbers = turns
        .filter(turn => ['friction', 'pivot', 'debug', 'fix'].includes(turn.tag) || turn.incomplete)
        .map(turn => turn.turnNumber)
        .sort((a, b) => b - a);
      const recentTurnNumbers = turns.slice(-8).map(turn => turn.turnNumber).reverse();

      const selected: number[] = [];
      const seen = new Set<number>();
      const addTurn = (turnNumber: number): void => {
        if (seen.has(turnNumber)) return;
        seen.add(turnNumber);
        selected.push(turnNumber);
      };

      for (const turnNumber of criticalTurnNumbers) {
        if (selected.length >= 6) break;
        addTurn(turnNumber);
      }
      for (const turnNumber of recentTurnNumbers) {
        if (selected.length >= 12) break;
        addTurn(turnNumber);
      }
      if (turns.length > 0 && selected.length < 12) {
        addTurn(1);
      }

      const sortedSelected = selected.sort((a, b) => a - b);
      const lines = [
        '## Turn Evidence (selected excerpts)',
        'Use these direct turn excerpts as grounding evidence when writing the analysis:',
        '',
      ];

      for (const turnNumber of sortedSelected) {
        const turn = turnMap.get(turnNumber);
        const detail = detailMap.get(turnNumber);
        if (!turn || !detail) continue;

        const status = turn.incomplete ? `, interrupted (${turn.terminationReason})` : '';
        lines.push(`### Turn ${turnNumber} [${turn.tag}] (${turn.toolCount} tools${status})`);
        lines.push(`User: ${detail.userMessage || '(no user text captured)'}`);
        lines.push(`Assistant: ${detail.assistantResponse || '(no assistant text captured)'}`);
        if (detail.tools.length > 0) {
          lines.push(`Tools: ${detail.tools.slice(0, 6).join(' | ')}`);
        } else {
          lines.push('Tools: none');
        }
        lines.push('');
      }

      return lines.join('\n');
    } catch (error) {
      logger.warn('Failed to build detailed turn evidence for review prompt', {
        sessionId: sessionId.slice(0, 8),
        error: error instanceof Error ? error.message : String(error),
      });
      return '';
    }
  }

  /**
   * Build detailed per-turn excerpts from unified messages.
   */
  private extractDetailedTurnEvidence(messages: UnifiedMessage[]): DetailedTurnEvidence[] {
    const humanTurnIndices: number[] = [];

    for (let i = 0; i < messages.length; i++) {
      const message = messages[i];
      if (message.role === 'user' && this.hasHumanTextUnified(message)) {
        humanTurnIndices.push(i);
      }
    }

    const extracted: DetailedTurnEvidence[] = [];

    for (let i = 0; i < humanTurnIndices.length; i++) {
      const startIdx = humanTurnIndices[i];
      const endIdx = i + 1 < humanTurnIndices.length ? humanTurnIndices[i + 1] : messages.length;
      const userMessage = messages[startIdx];
      const userText = this.clipPromptText(this.extractUnifiedText(userMessage), 260);
      if (!userText) continue;

      const assistantParts: string[] = [];
      const tools: string[] = [];
      const pendingTools = new Map<string, { name: string; input: string }>();

      for (let msgIdx = startIdx + 1; msgIdx < endIdx; msgIdx++) {
        const message = messages[msgIdx];

        for (const block of message.content) {
          if (message.role === 'assistant') {
            if (block.type === 'text' && block.text.trim()) {
              assistantParts.push(block.text);
            } else if (block.type === 'tool_use') {
              pendingTools.set(block.id, {
                name: block.name,
                input: this.summarizeToolInputForEvidence(block.name, block.input),
              });
            }
          } else if (message.role === 'user' && block.type === 'tool_result') {
            const tool = pendingTools.get(block.toolUseId);
            if (!tool) continue;

            tools.push(
              `${tool.name}(${tool.input}) -> ${this.summarizeToolResultForEvidence(block.output, block.isError)}`
            );
            pendingTools.delete(block.toolUseId);
          }
        }
      }

      for (const pending of pendingTools.values()) {
        tools.push(`${pending.name}(${pending.input}) -> pending`);
      }

      extracted.push({
        turnNumber: i + 1,
        userMessage: userText,
        assistantResponse: this.clipPromptText(assistantParts.join('\n\n'), 420),
        tools,
      });
    }

    return extracted;
  }

  private hasHumanTextUnified(message: UnifiedMessage): boolean {
    return message.content.some(block => block.type === 'text' && block.text.trim().length > 0);
  }

  private extractUnifiedText(message: UnifiedMessage): string {
    return message.content
      .filter(block => block.type === 'text')
      .map(block => block.text)
      .join(' ');
  }

  private summarizeToolInputForEvidence(toolName: string, input: Record<string, unknown>): string {
    if (toolName === 'Edit' || toolName === 'Write' || toolName === 'Read') {
      return this.clipPromptText(String(input.file_path ?? ''), 90) || 'unknown-file';
    }
    if (toolName === 'Bash') {
      return this.clipPromptText(String(input.command ?? ''), 90) || 'command';
    }
    if (toolName === 'Grep') {
      return `"${this.clipPromptText(String(input.pattern ?? ''), 60)}"`;
    }
    return this.clipPromptText(JSON.stringify(input), 80);
  }

  private summarizeToolResultForEvidence(output: string, isError?: boolean): string {
    if (isError) {
      return `error: ${this.clipPromptText(output, 80)}`;
    }
    return this.clipPromptText(output, 80) || 'ok';
  }

  private clipPromptText(value: string, maxLen: number): string {
    const compact = value.replace(/\s+/g, ' ').trim();
    if (compact.length <= maxLen) return compact;
    return compact.slice(0, maxLen - 3) + '...';
  }

  /**
   * Get recent git commits from the project directory.
   * This helps the LLM avoid recommending fixes that were already made.
   */
  private getRecentCommits(projectPath: string, hours: number = 24): string[] {
    try {
      // Check if it's a git repo
      execSync('git rev-parse --git-dir', { cwd: projectPath, stdio: 'pipe' });

      // Get commits from the last N hours with their messages and changed files
      const since = `${hours} hours ago`;
      const output = execSync(
        `git log --since="${since}" --pretty=format:"%h %s" --name-only 2>/dev/null | head -100`,
        { cwd: projectPath, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
      );

      if (!output.trim()) {
        return [];
      }

      // Parse output into readable format
      const lines = output.trim().split('\n');
      const commits: string[] = [];
      let currentCommit = '';
      let currentFiles: string[] = [];

      for (const line of lines) {
        if (line.match(/^[a-f0-9]{7,} /)) {
          // New commit line
          if (currentCommit) {
            commits.push(`${currentCommit}${currentFiles.length > 0 ? ` (files: ${currentFiles.slice(0, 5).join(', ')}${currentFiles.length > 5 ? '...' : ''})` : ''}`);
          }
          currentCommit = line;
          currentFiles = [];
        } else if (line.trim()) {
          // File path
          currentFiles.push(line.trim());
        }
      }
      // Don't forget the last commit
      if (currentCommit) {
        commits.push(`${currentCommit}${currentFiles.length > 0 ? ` (files: ${currentFiles.slice(0, 5).join(', ')}${currentFiles.length > 5 ? '...' : ''})` : ''}`);
      }

      logger.info('Retrieved recent commits', { projectPath, commitCount: commits.length });
      return commits;
    } catch (err) {
      logger.debug('Could not get recent commits (not a git repo or git error)', {
        projectPath,
        error: err instanceof Error ? err.message : String(err)
      });
      return [];
    }
  }

  /**
   * Summarize file changes into a digestible format for the LLM.
   * Groups by file and computes line statistics.
   */
  private summarizeFileChanges(changes: FileChange[]): FileChangeSummary[] {
    const byFile = new Map<string, FileChange[]>();

    for (const change of changes) {
      const existing = byFile.get(change.filePath) || [];
      existing.push(change);
      byFile.set(change.filePath, existing);
    }

    const summaries: FileChangeSummary[] = [];

    for (const [filePath, fileChanges] of byFile) {
      // Compute relative path
      const home = os.homedir();
      const relativePath = filePath.startsWith(`${home}/`) ? `~/${filePath.slice(home.length + 1)}` : filePath;

      // Collect turn numbers
      const turnNumbers = [...new Set(fileChanges.map(c => c.turnNumber))].sort((a, b) => a - b);

      // Count edits vs writes
      const editCount = fileChanges.filter(c => c.toolName === 'Edit').length;
      const writeCount = fileChanges.filter(c => c.toolName === 'Write').length;

      // Compute line stats
      let linesAdded = 0;
      let linesRemoved = 0;

      for (const change of fileChanges) {
        const newLines = (change.newString.match(/\n/g) || []).length + 1;
        const oldLines = change.oldString ? (change.oldString.match(/\n/g) || []).length + 1 : 0;

        if (change.toolName === 'Write') {
          linesAdded += newLines;
        } else {
          linesAdded += Math.max(0, newLines - oldLines);
          linesRemoved += Math.max(0, oldLines - newLines);
        }
      }

      // Generate a brief change summary from the first meaningful edit
      const changeSummary = this.generateChangeSummary(fileChanges);

      summaries.push({
        relativePath,
        turnNumbers,
        editCount,
        writeCount,
        linesAdded,
        linesRemoved,
        changeSummary,
      });
    }

    // Sort by first turn number
    return summaries.sort((a, b) => a.turnNumbers[0] - b.turnNumbers[0]);
  }

  /**
   * Generate a brief summary of what changed in a file.
   * Looks at the actual code changes to describe the modification.
   */
  private generateChangeSummary(changes: FileChange[]): string {
    // Find first non-trivial edit
    const meaningfulChange = changes.find(c => {
      if (c.toolName === 'Write') return true;
      // Skip tiny whitespace-only edits
      const oldTrimmed = (c.oldString || '').trim();
      const newTrimmed = c.newString.trim();
      return oldTrimmed !== newTrimmed && newTrimmed.length > 10;
    });

    if (!meaningfulChange) {
      return 'minor changes';
    }

    if (meaningfulChange.toolName === 'Write') {
      // New file - describe what it contains
      const content = meaningfulChange.newString;
      if (content.includes('export function')) return 'new function/utility';
      if (content.includes('export class')) return 'new class';
      if (content.includes('export const') || content.includes('export interface')) return 'new types/constants';
      if (content.includes('describe(') || content.includes('test(')) return 'new tests';
      return 'new file';
    }

    // Edit - try to describe the change
    const oldStr = meaningfulChange.oldString || '';
    const newStr = meaningfulChange.newString;

    // Look for common patterns
    if (!oldStr && newStr.includes('import')) return 'added imports';
    if (newStr.includes('try {') && !oldStr.includes('try {')) return 'added error handling';
    if (newStr.includes('await') && !oldStr.includes('await')) return 'made async';
    if (newStr.includes('if (') && !oldStr.includes('if (')) return 'added conditionals';
    if (newStr.length > oldStr.length * 1.5) return 'expanded logic';
    if (newStr.length < oldStr.length * 0.7) return 'simplified/removed code';

    // Check for function/variable renames
    const oldFuncs = oldStr.match(/function\s+(\w+)/g) || [];
    const newFuncs = newStr.match(/function\s+(\w+)/g) || [];
    if (oldFuncs.length > 0 && newFuncs.length > 0 && oldFuncs[0] !== newFuncs[0]) {
      return 'renamed function';
    }

    return 'modified';
  }

  /**
   * Format file changes section for the prompt.
   */
  private formatFileChangesForPrompt(summaries: FileChangeSummary[]): string {
    if (summaries.length === 0) {
      return '';
    }

    const lines = [
      '',
      '## Code Changes Made',
      'These are the actual files that were modified during the session:',
      '',
    ];

    for (const summary of summaries) {
      const stats = [];
      if (summary.editCount > 0) stats.push(`${summary.editCount} edit${summary.editCount > 1 ? 's' : ''}`);
      if (summary.writeCount > 0) stats.push(summary.writeCount > 1 ? `${summary.writeCount} writes` : 'new file');

      const lineStats = [];
      if (summary.linesAdded > 0) lineStats.push(`+${summary.linesAdded}`);
      if (summary.linesRemoved > 0) lineStats.push(`-${summary.linesRemoved}`);

      const turnInfo = summary.turnNumbers.length === 1
        ? `turn ${summary.turnNumbers[0]}`
        : `turns ${summary.turnNumbers[0]}-${summary.turnNumbers[summary.turnNumbers.length - 1]}`;

      lines.push(`- **${summary.relativePath}** (${stats.join(', ')}, ${lineStats.join('/')}, ${turnInfo})`);
      lines.push(`  → ${summary.changeSummary}`);
    }

    lines.push('');
    return lines.join('\n');
  }

  /**
   * Format friction/pivot/debug turns with extra context for better recommendations.
   */
  private formatFrictionTurnsForPrompt(frictionTurns: Turn[]): string {
    if (frictionTurns.length === 0) {
      return '';
    }

    const lines = [
      '',
      '## Notable Moments (friction, pivots, fixes)',
      'These turns involved challenges or course corrections - important context for recommendations:',
      '',
    ];

    for (const turn of frictionTurns) {
      const status = turn.incomplete ? ' (INTERRUPTED)' : '';
      const reason = turn.terminationReason !== 'normal_completion'
        ? ` [${turn.terminationReason.replace('_', ' ')}]`
        : '';

      lines.push(`**Turn ${turn.turnNumber} [${turn.tag}]${status}${reason}:** ${turn.headline}`);

      // Include more detail from actions
      if (turn.actions.length > 0) {
        const actionStr = turn.actions.slice(0, 5).map(a => `  - ${a}`).join('\n');
        lines.push(actionStr);
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Gather existing skills and past recommendations to inject into the review prompt.
   * This prevents the LLM from suggesting skills/guardrails that already exist.
   */
  private gatherExistingKnowledge(projectPath?: string): string {
    const sections: string[] = [];

    // 1. Scan existing skills (project + global + server cwd)
    const skillDirs = [
      projectPath ? path.join(projectPath, '.claude', 'skills') : null,
      path.join(process.cwd(), '.claude', 'skills'),
      path.join(process.env.HOME || '', '.claude', 'skills'),
    ].filter(Boolean) as string[];

    const skills: string[] = [];
    const seenSkills = new Set<string>();
    for (const dir of skillDirs) {
      try {
        if (!fs.existsSync(dir)) continue;
        const entries = fs.readdirSync(dir, { withFileTypes: true });
        for (const entry of entries) {
          if (!entry.isDirectory() || seenSkills.has(entry.name)) continue;
          seenSkills.add(entry.name);
          const skillFile = path.join(dir, entry.name, 'SKILL.md');
          try {
            const content = fs.readFileSync(skillFile, 'utf-8');
            const descMatch = content.match(/description:\s*(.+?)(?:\n---|$)/s);
            const desc = descMatch ? descMatch[1].trim().slice(0, 150) : '(no description)';
            skills.push(`- /${entry.name}: ${desc}`);
          } catch {
            skills.push(`- /${entry.name}`);
          }
        }
      } catch {
        // Directory doesn't exist or isn't readable
      }
    }

    if (skills.length > 0) {
      sections.push(`## Existing Skills (${skills.length} total)\nThese skills already exist. Do NOT recommend creating skills that duplicate these.\n\n${skills.join('\n')}`);
    }

    // 2. Query past recommendations from DB
    try {
      const MAX_RECS = 100;
      const allRecs = this.getAllRecommendations();
      if (allRecs.length > 0) {
        const recs = allRecs.slice(0, MAX_RECS);
        const recLines = recs.map(r => `- [${r.status}] ${r.friction}`);
        const truncNote = allRecs.length > MAX_RECS ? ` (showing most recent ${MAX_RECS})` : '';
        sections.push(`## Past Recommendations (${allRecs.length} total${truncNote})\nThese have already been recommended. Status shows whether the user completed, accepted, or dismissed each one. Do NOT recommend things that duplicate completed or accepted items. Use dismissed items as signal — the user chose not to act on these.\n\n${recLines.join('\n')}`);
      }
    } catch (err) {
      logger.debug('Could not query past recommendations', {
        error: err instanceof Error ? err.message : String(err),
      });
    }

    return sections.length > 0
      ? '\n' + sections.join('\n\n') + '\n'
      : '';
  }

  // ==========================================================================
  // Recommendation CRUD
  // ==========================================================================

  async acceptRecommendation(recommendation: {
    id: string;
    sessionId: string;
    target: string;
    improvementType?: string | null;
    friction: string;
    action: string;
    rationale: string;
    projectPath?: string | null;
    userNote?: string | null;
    sourceProject?: string | null;
    sourceMission?: string | null;
  }): Promise<void> {
    try {
      const fullSessionId = await this.sessionInfoService.resolveSessionId(recommendation.sessionId);
      if (!fullSessionId) {
        throw new Error(`Session not found: ${recommendation.sessionId}`);
      }

      let sourceProject = recommendation.sourceProject ?? null;
      let sourceMission = recommendation.sourceMission ?? null;
      if (!sourceProject) {
        try {
          const row = this.db.prepare('SELECT context FROM session_insights WHERE session_id = ?').get(fullSessionId) as { context?: string | null } | undefined;
          if (row?.context) {
            const ctx = parseJson(row.context) as { project?: string; mission?: string };
            sourceProject = ctx.project || null;
            sourceMission = sourceMission || ctx.mission || null;
          }
        } catch {
          // Best-effort — don't fail the accept if insights lookup fails
        }
      }

      const stmt = this.db.prepare(`
        INSERT OR REPLACE INTO recommendations (id, session_id, category, friction, suggestion, why, status, created_at, project_path, user_note, improvement_type, source_project, source_mission)
        VALUES (?, ?, ?, ?, ?, ?, 'accepted', ?, ?, ?, ?, ?, ?)
      `);
      stmt.run(
        recommendation.id,
        fullSessionId,
        recommendation.target,
        recommendation.friction,
        recommendation.action,
        recommendation.rationale,
        new Date().toISOString(),
        recommendation.projectPath ?? null,
        recommendation.userNote ?? null,
        recommendation.improvementType ?? null,
        sourceProject,
        sourceMission
      );
      logger.debug('Recommendation accepted', { id: recommendation.id, sessionId: fullSessionId, target: recommendation.target, sourceProject, hasUserNote: !!recommendation.userNote });
    } catch (error) {
      logger.error('Failed to accept recommendation', { error, id: recommendation.id });
      throw error;
    }
  }

  async dismissRecommendation(recommendationId: string): Promise<void> {
    try {
      const stmt = this.db.prepare(`
        UPDATE recommendations SET status = 'dismissed', actioned_at = ?
        WHERE id = ?
      `);
      const result = stmt.run(new Date().toISOString(), recommendationId);

      if (result.changes === 0) {
        logger.debug('Recommendation not found, cannot dismiss', { id: recommendationId });
      } else {
        logger.debug('Recommendation dismissed', { id: recommendationId });
      }
    } catch (error) {
      logger.error('Failed to dismiss recommendation', { error, id: recommendationId });
      throw error;
    }
  }

  async completeRecommendation(recommendationId: string): Promise<void> {
    try {
      const stmt = this.db.prepare(`
        UPDATE recommendations SET status = 'completed', actioned_at = ?
        WHERE id = ?
      `);
      stmt.run(new Date().toISOString(), recommendationId);
      logger.debug('Recommendation completed', { id: recommendationId });
    } catch (error) {
      logger.error('Failed to complete recommendation', { error, id: recommendationId });
      throw error;
    }
  }

  async getPendingRecommendations(): Promise<StoredRecommendation[]> {
    try {
      const rows = this.db.prepare(`
        SELECT id, session_id, category, friction, suggestion, why, status, created_at, project_path, user_note, improvement_type, source_project, source_mission
        FROM recommendations
        WHERE status = 'accepted'
        ORDER BY created_at DESC
      `).all() as Array<{
        id: string;
        session_id: string;
        category: string;
        friction: string;
        suggestion: string;
        why: string;
        status: string;
        created_at: string;
        project_path: string | null;
        user_note: string | null;
        improvement_type: string | null;
        source_project: string | null;
        source_mission: string | null;
      }>;

      // Bulk-fetch session insights for rows missing source_project (lazy backfill)
      const needsBackfill = rows.filter(r => !r.source_project);
      const insightsLookup = new Map<string, { project: string | null; mission: string | null }>();
      if (needsBackfill.length > 0) {
        const sessionIds = [...new Set(needsBackfill.map(r => r.session_id))];
        for (const sid of sessionIds) {
          try {
            const row = this.db.prepare('SELECT context FROM session_insights WHERE session_id = ?').get(sid) as { context?: string | null } | undefined;
            if (row?.context) {
              const ctx = parseJson(row.context) as { project?: string; mission?: string };
              insightsLookup.set(sid, {
                project: ctx.project || null,
                mission: ctx.mission || null,
              });
            }
          } catch {
            // Best-effort backfill
          }
        }
      }

      return rows.map(row => {
        let sourceProject = row.source_project;
        let sourceMission = row.source_mission;

        if (!sourceProject) {
          const backfill = insightsLookup.get(row.session_id);
          if (backfill) {
            sourceProject = backfill.project;
            sourceMission = sourceMission || backfill.mission;
          }
        }

        return {
          id: row.id,
          sessionId: row.session_id,
          target: (row.category || 'global_instructions') as StoredRecommendation['target'],
          improvementType: (row.improvement_type || undefined) as StoredRecommendation['improvementType'],
          friction: row.friction,
          action: row.suggestion,
          rationale: row.why,
          status: row.status as StoredRecommendation['status'],
          createdAt: row.created_at,
          projectPath: row.project_path,
          userNote: row.user_note,
          sourceProject,
          sourceMission,
        };
      });
    } catch (error) {
      logger.error('Failed to get pending recommendations', { error });
      return [];
    }
  }

  getAllRecommendations(): Array<{ friction: string; status: string }> {
    try {
      return this.db.prepare(`
        SELECT friction, status FROM recommendations ORDER BY created_at DESC
      `).all() as Array<{ friction: string; status: string }>;
    } catch (error) {
      logger.error('Failed to get all recommendations', { error });
      return [];
    }
  }

  async getRecommendationsForSession(sessionId: string): Promise<Omit<StoredRecommendation, 'sessionId'>[]> {
    try {
      const rows = this.db.prepare(`
        SELECT id, category, friction, suggestion, why, status, created_at, project_path
        FROM recommendations
        WHERE session_id = ? OR session_id LIKE ?
        ORDER BY created_at DESC
      `).all(sessionId, `${sessionId}%`) as Array<{
        id: string;
        category: string;
        friction: string;
        suggestion: string;
        why: string;
        status: string;
        created_at: string;
        project_path: string | null;
      }>;

      return rows.map(row => ({
        id: row.id,
        target: (row.category || 'global_instructions') as StoredRecommendation['target'],
        friction: row.friction,
        action: row.suggestion,
        rationale: row.why,
        status: row.status as StoredRecommendation['status'],
        createdAt: row.created_at,
        projectPath: row.project_path,
      }));
    } catch (error) {
      logger.error('Failed to get recommendations for session', { error, sessionId });
      return [];
    }
  }
}
