import fs from 'fs';
import os from 'os';
import path from 'path';
import { parseJson } from '../../utils/json.js';
import { getHostIntegration, HOST_INTEGRATION_FILENAME } from './host-integration.js';
import { LatticeError } from '../../types/index.js';

interface ClaudeHookMatcher {
  matcher?: string;
  hooks?: Array<Record<string, unknown>>;
}

export interface ClaudeSettings {
  toolPermissions?: {
    allow?: string[];
    deny?: string[];
  };
  hooks?: Record<string, ClaudeHookMatcher[]>;
  [key: string]: unknown;
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function buildPreCompactHookScript(params: {
  endpointUrl: string;
  authToken?: string;
}): string {
  const endpointLiteral = shellSingleQuote(params.endpointUrl);
  const authHeaderLiteral = params.authToken
    ? shellSingleQuote(`Authorization: Bearer ${params.authToken}`)
    : "''";

  return `#!/bin/bash
# Auto-generated by Lattice. Manual edits may be overwritten.

LOG="/tmp/lattice-pre-compact-hook.log"
ENDPOINT=${endpointLiteral}
AUTH_HEADER=${authHeaderLiteral}

input=$(cat)
echo "$(date -Iseconds) hook fired, input=$(printf '%s' "$input" | head -c 500)" >> "$LOG"

session_id=$(printf '%s' "$input" | jq -r '.session_id // empty' 2>/dev/null)
trigger=$(printf '%s' "$input" | jq -r '.trigger // "unknown"' 2>/dev/null)

if [ -z "$session_id" ]; then
  echo "$(date -Iseconds) no session_id, exiting" >> "$LOG"
  exit 0
fi

payload=$(jq -cn --arg session_id "$session_id" --arg trigger "$trigger" '{session_id:$session_id, trigger:$trigger, phase:"starting"}')
curl_args=(-s -X POST "$ENDPOINT" -H 'Content-Type: application/json' --max-time 2)

if [ -n "$AUTH_HEADER" ]; then
  curl_args+=(-H "$AUTH_HEADER")
fi

echo "$(date -Iseconds) posting to ${params.endpointUrl} session_id=$session_id trigger=$trigger" >> "$LOG"

curl "\${curl_args[@]}" -d "$payload" >> "$LOG" 2>&1 &

exit 0
`;
}

export class ClaudeSettingsService {
  private static instance: ClaudeSettingsService | null = null;
  private readonly settingsPath: string;
  private readonly lockPath: string;

  private constructor() {
    this.settingsPath = path.join(os.homedir(), '.claude', 'settings.json');
    this.lockPath = `${this.settingsPath}.lock`;
  }

  static getInstance(): ClaudeSettingsService {
    if (!ClaudeSettingsService.instance) {
      ClaudeSettingsService.instance = new ClaudeSettingsService();
    }
    return ClaudeSettingsService.instance;
  }

  getSettingsPath(): string {
    return this.settingsPath;
  }

  loadSettings(options?: { throwOnParseError?: boolean }): ClaudeSettings {
    if (!fs.existsSync(this.settingsPath)) {
      return {};
    }

    try {
      const data = fs.readFileSync(this.settingsPath, 'utf-8');
      return parseJson(data) as ClaudeSettings;
    } catch (error) {
      if (options?.throwOnParseError) {
        throw error;
      }
      return {};
    }
  }

  /**
   * Every write to shared ~/.claude state funnels through saveSettings or
   * ensureManagedExecutable, so the authority check lives on those two rather
   * than on each caller. A write path added later inherits the check instead of
   * having to remember it.
   */
  private assertMayWriteHostState(target: string): void {
    const authority = getHostIntegration();
    if (authority.manageClaudeSettings) return;

    throw new LatticeError(
      'HOST_SETTINGS_NOT_MANAGED',
      `Refusing to write shared Claude state at ${target}: ${authority.deniedReason}. `
      + `Only a Lattice instance whose config dir carries a matching `
      + `${HOST_INTEGRATION_FILENAME} may change machine-wide hooks.`,
      409
    );
  }

  saveSettings(settings: ClaudeSettings): void {
    this.assertMayWriteHostState(this.settingsPath);
    const dir = path.dirname(this.settingsPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(this.settingsPath, JSON.stringify(settings, null, 2));
  }

  private withSettingsLock<T>(fn: () => T): T {
    const dir = path.dirname(this.settingsPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const startedAt = Date.now();
    const timeoutMs = 5000;
    const retryDelayMs = 50;
    let lockFd: number | null = null;

    while (lockFd === null) {
      try {
        lockFd = fs.openSync(this.lockPath, 'wx');
      } catch (error) {
        const err = error as NodeJS.ErrnoException;
        if (err.code !== 'EEXIST') {
          throw error;
        }

        if (Date.now() - startedAt > timeoutMs) {
          throw new Error(`Timed out acquiring Claude settings lock: ${this.lockPath}`);
        }

        Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, retryDelayMs);
      }
    }

    try {
      return fn();
    } finally {
      try {
        fs.closeSync(lockFd);
      } catch {
        // Best-effort lock cleanup.
      }
      try {
        fs.unlinkSync(this.lockPath);
      } catch {
        // Best-effort lock cleanup.
      }
    }
  }

  private updateSettings(updater: (settings: ClaudeSettings) => ClaudeSettings): ClaudeSettings {
    // Before withSettingsLock, which mkdirs ~/.claude and creates a lock file.
    // An instance with no authority should leave no trace at all, and a lock
    // taken by a process that is about to refuse the write is a lock other
    // instances wait on for nothing.
    this.assertMayWriteHostState(this.settingsPath);
    return this.withSettingsLock(() => {
      const current = this.loadSettings({ throwOnParseError: true });
      const next = updater(current);
      this.saveSettings(next);
      return next;
    });
  }

  private ensureManagedExecutable(filePath: string, contents: string): boolean {
    this.assertMayWriteHostState(filePath);
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const current = fs.existsSync(filePath)
      ? fs.readFileSync(filePath, 'utf-8')
      : null;
    const needsWrite = current !== contents;

    if (needsWrite) {
      fs.writeFileSync(filePath, contents, 'utf-8');
    }

    const stats = fs.statSync(filePath);
    const desiredMode = 0o755;
    const currentMode = stats.mode & 0o777;
    if (currentMode !== desiredMode) {
      fs.chmodSync(filePath, desiredMode);
      return true;
    }

    return needsWrite;
  }

  getToolPermissionsAllow(options?: { throwOnParseError?: boolean }): string[] {
    const settings = this.loadSettings(options);
    const allow = settings.toolPermissions?.allow;
    if (!Array.isArray(allow)) {
      return [];
    }

    return allow
      .filter((entry): entry is string => typeof entry === 'string')
      .map((entry) => entry.trim())
      .filter((entry) => entry.length > 0);
  }

  setToolPermissionsAllow(patterns: string[]): void {
    this.updateSettings((settings) => {
      if (!settings.toolPermissions) {
        settings.toolPermissions = {};
      }
      settings.toolPermissions.allow = patterns;
      return settings;
    });
  }

  /**
   * Apply a single HTTP hook update to a settings object (no I/O).
   * Returns true if the settings were modified.
   */
  private applyManagedHttpHook(
    settings: ClaudeSettings,
    eventName: string,
    url: string,
    managedHeaderName: string,
    desiredAuthHeader: string | null
  ): boolean {
    const managedHeaderValue = 'v1';
    let changed = false;

    if (!settings.hooks || typeof settings.hooks !== 'object') {
      settings.hooks = {};
    }

    const existing = Array.isArray(settings.hooks[eventName])
      ? settings.hooks[eventName]
      : [];

    const normalizedMatchers = existing.map((matcher) => ({
      ...matcher,
      hooks: Array.isArray(matcher.hooks) ? matcher.hooks : [],
    }));

    let found = false;
    for (const matcher of normalizedMatchers) {
      for (const hook of matcher.hooks ?? []) {
        if (
          hook
          && typeof hook === 'object'
          && hook.type === 'http'
          && typeof (hook as { url?: unknown }).url === 'string'
          && ((hook as { url: string }).url === url
            || (hook as { headers?: Record<string, string> }).headers?.[managedHeaderName] === managedHeaderValue)
        ) {
          found = true;
          const candidate = hook as {
            type?: string;
            url?: string;
            timeout?: number;
            headers?: Record<string, string>;
            allowedEnvVars?: string[];
          };
          if (candidate.url !== url) {
            candidate.url = url;
            changed = true;
          }
          if (candidate.timeout !== 600000) {
            candidate.timeout = 600000;
            changed = true;
          }
          const nextHeaders = { ...(candidate.headers ?? {}) };
          if (nextHeaders[managedHeaderName] !== managedHeaderValue) {
            nextHeaders[managedHeaderName] = managedHeaderValue;
            changed = true;
          }
          if (desiredAuthHeader) {
            if (nextHeaders.Authorization !== desiredAuthHeader) {
              nextHeaders.Authorization = desiredAuthHeader;
              changed = true;
            }
          } else if ('Authorization' in nextHeaders) {
            delete nextHeaders.Authorization;
            changed = true;
          }
          candidate.headers = nextHeaders;
        }
      }
    }

    if (!found) {
      normalizedMatchers.push({
        matcher: '.*',
        hooks: [
          {
            type: 'http',
            url,
            timeout: 300000,
            headers: {
              [managedHeaderName]: managedHeaderValue,
              ...(desiredAuthHeader ? { Authorization: desiredAuthHeader } : {}),
            },
          },
        ],
      });
      changed = true;
    }

    settings.hooks[eventName] = normalizedMatchers;
    return changed;
  }

  /**
   * Ensure a global PermissionRequest HTTP hook exists and points to Lattice.
   * Returns true when settings changed.
   */
  ensurePermissionRequestHook(url: string, options?: { authToken?: string }): boolean {
    let changed = false;
    this.updateSettings((settings) => {
      changed = this.applyManagedHttpHook(
        settings, 'PermissionRequest', url, 'X-Lattice-Permission-Hook',
        options?.authToken ? `Bearer ${options.authToken}` : null
      );
      return settings;
    });
    return changed;
  }

  /**
   * Ensure a global PreToolUse HTTP hook exists and points to Lattice.
   * Returns true when settings changed.
   */
  ensurePreToolUseHook(url: string, options?: { authToken?: string }): boolean {
    let changed = false;
    this.updateSettings((settings) => {
      changed = this.applyManagedHttpHook(
        settings, 'PreToolUse', url, 'X-Lattice-PreToolUse-Hook',
        options?.authToken ? `Bearer ${options.authToken}` : null
      );
      return settings;
    });
    return changed;
  }

  /**
   * Batch-ensure multiple HTTP hooks in a single read-write cycle.
   * Returns per-hook change flags.
   */
  ensureHttpHooksBatch(hooks: Array<{
    eventName: string;
    url: string;
    managedHeaderName: string;
    authToken?: string;
  }>): Record<string, boolean> {
    const results: Record<string, boolean> = {};
    this.updateSettings((settings) => {
      for (const hook of hooks) {
        results[hook.eventName] = this.applyManagedHttpHook(
          settings, hook.eventName, hook.url, hook.managedHeaderName,
          hook.authToken ? `Bearer ${hook.authToken}` : null
        );
      }
      return settings;
    });
    return results;
  }

  /**
   * Ensure a global PreCompact command hook exists.
   * PreCompact only supports command hooks (not HTTP).
   * Returns true when settings changed.
   */
  ensurePreCompactHook(params: {
    scriptPath: string;
    endpointUrl: string;
    authToken?: string;
  }): boolean {
    const scriptChanged = this.ensureManagedExecutable(
      params.scriptPath,
      buildPreCompactHookScript({
        endpointUrl: params.endpointUrl,
        authToken: params.authToken,
      })
    );
    let settingsChanged = false;

    this.updateSettings((settings) => {
      if (!settings.hooks || typeof settings.hooks !== 'object') {
        settings.hooks = {};
      }

      const existing = Array.isArray(settings.hooks['PreCompact'])
        ? settings.hooks['PreCompact']
        : [];

      // Look for an existing Lattice-managed command hook by script path pattern
      for (const matcher of existing) {
        for (const hook of (matcher.hooks ?? [])) {
          if (
            hook
            && typeof hook === 'object'
            && hook.type === 'command'
            && typeof (hook as { command?: unknown }).command === 'string'
            && (hook as { command: string }).command.includes('pre-compact-hook')
          ) {
            // Already registered — update path if changed
            if ((hook as { command: string }).command !== params.scriptPath) {
              (hook as { command: string }).command = params.scriptPath;
              settingsChanged = true;
            }
            settings.hooks['PreCompact'] = existing;
            return settings;
          }
        }
      }

      // Not found — add a new matcher group
      existing.push({
        matcher: '.*',
        hooks: [{ type: 'command', command: params.scriptPath }],
      });
      settings.hooks['PreCompact'] = existing;
      settingsChanged = true;
      return settings;
    });

    return scriptChanged || settingsChanged;
  }
}
